version: '3'
services:
  jupyter:
    build:
      context: ./jupyter-docker
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    container_name: jupyter
    volumes:
      - ..:/home/jovyan/work:cached
