version: '3'
services:
  jupyter:
    build:
      context: ./jupyter-docker
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    container_name: jupyter
    volumes:
      - ..:/home/jovyan/work:cached
  pgadmin:
    build:
      context: ./pgadmin-docker
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: jovyan@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    container_name: pgadmin

volumes:
  pgadmin: